import Providers from "./providers";
import "../styles/index.css";
import { Vollkorn, Goblin_One } from "next/font/google";
import PageTransition from "@/components/PageTransition";

const vollkorn = Vollkorn({
  subsets: ["latin"],
  variable: "--font-vollkorn",
});

const goblinOne = Goblin_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goblin",
});

export const metadata = {
  title: "Carpooling",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vollkorn.variable} ${goblinOne.variable}`}>
        <Providers>
          <PageTransition>{children}</PageTransition>
        </Providers>
      </body>
    </html>
  );
}
