import Providers from "./providers";
import "../styles/index.css";
import { Vollkorn, Goblin_One } from "next/font/google";
import PageTransition from "@/components/PageTransition";
import { getMe } from "@/services/server/authService";
import LocationPermissionModal from "@/components/LocationAcess";
import ReactQueryProvider from "@/components/QueryProvider";
import NotificationProvider from "@/components/notifications/NotificationProvider";
import { Toaster } from "sonner";
import "@/styles/notification-toast.css";
import SocketProvider from "@/components/SocketProvider";

const vollkorn = Vollkorn({
  subsets: ["latin"],
  variable: "--font-vollkorn",
});

const goblinOne = Goblin_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goblin",
});

export const metadata = {
  title: "Carpooling",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({ children }) {
  let userData = null;

  try {
    const response = await getMe();
    userData = response?.data?.user || null;
  } catch (error) {
    userData = null;
  }

  return (
    <html lang="en">
      <body className={`${vollkorn.variable} ${goblinOne.variable}`}>
        <ReactQueryProvider>
          <Providers userData={userData}>
            <SocketProvider />
            <LocationPermissionModal />
            <PageTransition>
              <NotificationProvider />
              {children}
              <Toaster
                position="top-right"
                richColors
                closeButton
                duration={5000}
              />
            </PageTransition>
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
