import Providers from "./providers";
import "../styles/index.css";
import { Vollkorn, Goblin_One } from "next/font/google";

const vollkorn = Vollkorn({
  subsets: ["latin"],
  variable: "--font-vollkorn",
});

const goblinOne = Goblin_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goblin",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vollkorn.variable} ${goblinOne.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
